//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJERCICIOMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Autor
    {
        public int id { get; set; }
        [DisplayName("TIPO DE IDENTIFICACION")]
        public string AU_TipoIdentificador { get; set; }
        [DisplayName("CODIGO AUTOR")]
        public string AU_Identificacion { get; set; }
        [DisplayName("NOMBRE DEL AUTOR")]
        public string AU_Nombre { get; set; }
        public System.DateTime AU_FechaCreacion { get; set; }
        public Nullable<System.DateTime> AU_FechaModificacion { get; set; }
        public string AU_UsuarioCreacion { get; set; }
        public string AU_UsuarioModificacion { get; set; }
        [DisplayName("ESTADO")]
        public int AU_Estado { get; set; }
    }
}
