//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJERCICIOMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bibliosafeEntities : DbContext
    {
        public bibliosafeEntities()
            : base("name=bibliosafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Ejemplar> Ejemplar { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<PrestamoUsuario> PrestamoUsuario { get; set; }
        public virtual DbSet<Reparacion> Reparacion { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<Libros_Por_Autor> Libros_Por_Autor { get; set; }
        public virtual DbSet<SUMATORIATIEMPOS> SUMATORIATIEMPOS { get; set; }
    
        public virtual ObjectResult<EJEMPLARESINTERVALO_Result> EJEMPLARESINTERVALO(Nullable<System.DateTime> sTARTTIME, Nullable<System.DateTime> fINISHTIME)
        {
            var sTARTTIMEParameter = sTARTTIME.HasValue ?
                new ObjectParameter("STARTTIME", sTARTTIME) :
                new ObjectParameter("STARTTIME", typeof(System.DateTime));
    
            var fINISHTIMEParameter = fINISHTIME.HasValue ?
                new ObjectParameter("FINISHTIME", fINISHTIME) :
                new ObjectParameter("FINISHTIME", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EJEMPLARESINTERVALO_Result>("EJEMPLARESINTERVALO", sTARTTIMEParameter, fINISHTIMEParameter);
        }
    
        public virtual ObjectResult<LIBROSPORUSUARIO_Result> LIBROSPORUSUARIO(Nullable<System.DateTime> sTARTTIME, Nullable<System.DateTime> fINISHTIME)
        {
            var sTARTTIMEParameter = sTARTTIME.HasValue ?
                new ObjectParameter("STARTTIME", sTARTTIME) :
                new ObjectParameter("STARTTIME", typeof(System.DateTime));
    
            var fINISHTIMEParameter = fINISHTIME.HasValue ?
                new ObjectParameter("FINISHTIME", fINISHTIME) :
                new ObjectParameter("FINISHTIME", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LIBROSPORUSUARIO_Result>("LIBROSPORUSUARIO", sTARTTIMEParameter, fINISHTIMEParameter);
        }
    }
}
