//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJERCICIOMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Ejemplar
    {
        public int Id { get; set; }
        [DisplayName("Nombre Libro")]
        public string EJ_NombreLibro { get; set; }
        [DisplayName("Codigo Ejemplar")]
        public string EJ_CodigoEjemplar { get; set; }
        [DisplayName("Codigo Libro")]
        public string EJ_CodigoLibro { get; set; }
        [DisplayName("Estado ")]
        public int EJ_Estado { get; set; }
        public System.DateTime EJ_FechaCreacion { get; set; }
        public Nullable<System.DateTime> EJ_FechaModificacion { get; set; }
        public string EJ_UsuarioCreacion { get; set; }
        public string EJ_UsuarioModificacion { get; set; }
        [DisplayName("Tipo de Ejemplar")]
        public string EJ_TipoEjemplar { get; set; }
        [DisplayName("Estado Sistema")]
        public Nullable<bool> EJ_EstadoSistema { get; set; }
    }
}
