//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJERCICIOMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public string Libro { get; set; }
        public string NombreLibro { get; set; }
        public Nullable<int> NumEjemplar { get; set; }
        public string Ejemplareslibres { get; set; }
        public string EjemplaresPrestados { get; set; }
        public string EjemplaresReparacion { get; set; }
    }
}
