//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJERCICIOMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoUsuario
    {
        public int id { get; set; }
        public string PU_CodigoUsuario { get; set; }
        public string PU_NombreEjemplar { get; set; }
        public string PU_CodigoEjemplar { get; set; }
        public System.DateTime PU_FechaExtraccion { get; set; }
        public Nullable<System.DateTime> PU_FechaDevolucion { get; set; }
        public int PU_PrestamoActual { get; set; }
        public string PU_EstadoDevolucion { get; set; }
        public System.DateTime PU_FechaCreacion { get; set; }
        public System.DateTime PU_FechaModificacion { get; set; }
        public string PU_UsuarioCreacion { get; set; }
        public string PU_UsuarioModificacion { get; set; }
        public int PU_Estado { get; set; }
    }
}
