//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJERCICIOMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparacion
    {
        public int id { get; set; }
        public string RE_EjemplarCodigo { get; set; }
        public string RE_EstadoInicial { get; set; }
        public System.DateTime RE_InicioReparacion { get; set; }
        public Nullable<System.DateTime> RE_FinalizacionReparacion { get; set; }
        public string RE_EstadoActualFisico { get; set; }
        public int RE_Estado { get; set; }
        public Nullable<System.DateTime> RE_FechaReIncorporacion { get; set; }
        public System.DateTime RE_FechaCreacion { get; set; }
        public Nullable<System.DateTime> RE_FechaModificacion { get; set; }
        public string RE_UsuarioCreacion { get; set; }
        public string RE_UsuarioModificacion { get; set; }
    }
}
