//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJERCICIOMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Usuario
    {
        public int Id { get; set; }
        [DisplayName("CODIGO USUARIO")]
        public string US_Codigo { get; set; }
        [DisplayName("NOMBRE USUARIO")]
        public string US_Nombre { get; set; }
        [DisplayName("CONTRASEÑA")]
        public string US_Password { get; set; }
        [DisplayName("ESTADO")]
        public int US_Estado { get; set; }
        public System.DateTime US_FechaCreacion { get; set; }
        public System.DateTime US_FechaModificacion { get; set; }
        public string US_UsuarioCreacion { get; set; }
        public string US_UsuarioModificacion { get; set; }
        [DisplayName("CORREO ELECTRONICO")]
        public string US_Email { get; set; }
        [DisplayName("TIPO DOCUMENTO")]
        public string US_Tipodedocumento { get; set; }
        [DisplayName("DOCUMENTO")]
        public string US_Documento { get; set; }
    }
}
